### ISSUE TITLE
Error in the description

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [zifnab87/ra-component-factory#10]
"ra-component-factory when used with http://github.com/marmelab/**admin-on-rest** provides a"
maybe **react-admin**?

**Comment by Pomazan-Bogdan** [comment]
![image](https://user-images.githubusercontent.com/696713/52555915-b3e5de80-2df3-11e9-9cda-72f0e6acea41.png)

**Comment by zifnab87** [comment]
Thank you - fixed it
